### ISSUE TITLE
Check pull requests in development branche

### ISSUE THREAD

**Issue by Fesch-star** [Fesch-star/CM_analysis#46]
Hi Jelle, 

I made some more changes over the past days and pushed them to the development branche. Somehow they all appear below each other  and make up one layered (?) pull request.

Could you check the changes and see if they can be merged into main? The second commit does not pass all test, I expect the third also not to pass as I changed 3 functions.
Thanks, Femke

**Comment by jelletreep** [comment]
Hi @Fesch-star,
Yes, until someone merges the Pull request (PR), it is still possible to add new commits to the branch and the PR will be automatically updated. This is handy since it is good practice to let someone review a PR, and if the review leads to revisions it is ease to implement them before merging. When merging we can still decide to keep all the original commits of the development branch, or 'Squash' all changes into one commit. I have made some changes to the development branch to fix the Package build issues. I will add a message to the pull request, and then you can merge it!

**Comment by Fesch-star** [comment]
checked and merged the pull request
